"""empty message

Revision ID: 58f4010a177b
Revises: 8f38cccdd187
Create Date: 2018-08-17 22:13:18.323324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f4010a177b'
down_revision = '8f38cccdd187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_game_id', table_name='item')
    op.create_index(op.f('ix_item_game_id'), 'item', ['game_id'], unique=False)
    op.drop_index('ix_item_name', table_name='item')
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.create_index('ix_item_name', 'item', ['name'], unique=1)
    op.drop_index(op.f('ix_item_game_id'), table_name='item')
    op.create_index('ix_item_game_id', 'item', ['game_id'], unique=1)
    # ### end Alembic commands ###
