"""items table

Revision ID: 8f38cccdd187
Revises: 
Create Date: 2018-08-17 18:10:43.446617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f38cccdd187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('members', sa.Boolean(), nullable=True),
    sa.Column('buy_avg', sa.Integer(), nullable=True),
    sa.Column('sell_avg', sa.Integer(), nullable=True),
    sa.Column('buy_vol', sa.Integer(), nullable=True),
    sa.Column('sell_vol', sa.Integer(), nullable=True),
    sa.Column('total_vol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_buy_avg'), 'item', ['buy_avg'], unique=False)
    op.create_index(op.f('ix_item_buy_vol'), 'item', ['buy_vol'], unique=False)
    op.create_index(op.f('ix_item_game_id'), 'item', ['game_id'], unique=True)
    op.create_index(op.f('ix_item_members'), 'item', ['members'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=True)
    op.create_index(op.f('ix_item_price'), 'item', ['price'], unique=False)
    op.create_index(op.f('ix_item_sell_avg'), 'item', ['sell_avg'], unique=False)
    op.create_index(op.f('ix_item_sell_vol'), 'item', ['sell_vol'], unique=False)
    op.create_index(op.f('ix_item_total_vol'), 'item', ['total_vol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_total_vol'), table_name='item')
    op.drop_index(op.f('ix_item_sell_vol'), table_name='item')
    op.drop_index(op.f('ix_item_sell_avg'), table_name='item')
    op.drop_index(op.f('ix_item_price'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_members'), table_name='item')
    op.drop_index(op.f('ix_item_game_id'), table_name='item')
    op.drop_index(op.f('ix_item_buy_vol'), table_name='item')
    op.drop_index(op.f('ix_item_buy_avg'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
